import {
  ChangeDetectionStrategy,
  Component,
  inject,
  input,
  linkedSignal,
  signal,
} from "@angular/core";
import { MatButton } from "@angular/material/button";
import { MatCard, MatCardContent } from "@angular/material/card";
import { MatProgressSpinner } from "@angular/material/progress-spinner";
import { finalize } from "rxjs";
import { BookService } from "src/app/services/book.service";

/**
 * Shows an AI-written summary of a book. The text is generated by the server: the AI service's key never reaches the
 * browser, and the server (not this component) decides what is asked about the book.
 */
@Component({
  selector: "app-book-summary",
  templateUrl: "./book-summary.component.html",
  styleUrls: ["./book-summary.component.scss"],
  imports: [MatCard, MatCardContent, MatButton, MatProgressSpinner],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class BookSummaryComponent {
  private readonly bookService = inject(BookService);

  readonly bookId = input.required<number>();

  // Both start empty again whenever the component is shown another book.
  readonly bookSummary = linkedSignal<number, string>({
    source: this.bookId,
    computation: () => "",
  });
  readonly errorMessage = linkedSignal<number, string>({
    source: this.bookId,
    computation: () => "",
  });
  readonly showLoader = signal(false);

  fetchSummary() {
    this.showLoader.set(true);
    this.bookSummary.set("");
    this.errorMessage.set("");

    this.bookService
      .getBookSummary(this.bookId())
      .pipe(finalize(() => this.showLoader.set(false)))
      .subscribe({
        next: (result) => this.bookSummary.set(result.summary),
        error: () =>
          this.errorMessage.set(
            "A summary could not be generated right now. Please try again in a minute."
          ),
      });
  }
}
