@echo off
rem Production release on this machine, in one go:
rem   1. publish the binaries            -> artifacts\publish
rem   2. build the Docker image          -> bookcart:latest and bookcart:<yyyyMMdd-HHmm>
rem   3. start SQL Server (Docker Compose, data in a volume)
rem   4. back up an existing database, then apply the EF Core migrations (asks first)
rem   5. start the app container         -> http://localhost:8080 (APP_PORT in deploy\.env)
rem   6. wait for /health
rem First run creates deploy\.env with generated secrets (git-ignored). Run with /y to skip the confirmation.
setlocal EnableExtensions
set "AUTO_YES="
if /i "%~1"=="/y" set "AUTO_YES=1"

for %%i in ("%~dp0..") do set "ROOT=%%~fi"
set "DEPLOY=%ROOT%\deploy"
set "ENVFILE=%DEPLOY%\.env"
set COMPOSE=docker compose --env-file "%ENVFILE%" -f "%DEPLOY%\docker-compose.yml"

echo ===== BookCart production release =====
call "%~dp0lib\ensure-docker.bat"
if errorlevel 1 goto fail

if not exist "%ENVFILE%" call :make_env
if errorlevel 1 goto fail
for /f "usebackq eol=# tokens=1,* delims==" %%a in ("%ENVFILE%") do set "%%a=%%b"
if "%SA_PASSWORD%"=="" (
  echo SA_PASSWORD is empty in deploy\.env
  goto fail
)
if "%JWT_SECRET%"=="" (
  echo JWT_SECRET is empty in deploy\.env
  goto fail
)
if "%APP_PORT%"=="" set "APP_PORT=8080"
if "%SQL_PORT%"=="" set "SQL_PORT=14331"

for /f %%t in ('powershell -NoProfile -Command "Get-Date -Format yyyyMMdd-HHmm"') do set "TAG=%%t"
set "BOOKCART_TAG=%TAG%"
echo Release tag: %TAG%

echo.
echo [1/6] Publishing the binaries to artifacts\publish ...
if exist "%ROOT%\artifacts\publish" rmdir /s /q "%ROOT%\artifacts\publish"
dotnet publish "%ROOT%\BookCart\BookCart.csproj" -c Release -o "%ROOT%\artifacts\publish" --nologo -v:minimal
if errorlevel 1 goto fail

echo.
echo [2/6] Building the Docker image bookcart:%TAG% ...
dotnet publish "%ROOT%\BookCart\BookCart.csproj" -c Release --os linux --arch x64 -t:PublishContainer -p:ContainerImageTags=\"latest;%TAG%\" --nologo -v:minimal
if errorlevel 1 goto fail

echo.
echo [3/6] Starting SQL Server ...
%COMPOSE% up -d --wait sqlserver
if errorlevel 1 goto fail

echo.
echo [4/6] Database
set "DBEXISTS=0"
for /f "usebackq delims=" %%r in (`docker exec -e "SQLCMDPASSWORD=%SA_PASSWORD%" bookcart-sql /opt/mssql-tools18/bin/sqlcmd -C -S localhost -U sa -h -1 -W -Q "SET NOCOUNT ON; SELECT CASE WHEN DB_ID('BookDB') IS NULL THEN 0 ELSE 1 END"`) do set "DBEXISTS=%%r"
if "%DBEXISTS%"=="1" (
  call :backup
  if errorlevel 1 goto fail
) else (
  echo No database yet: the migrations will create it.
)
if defined AUTO_YES goto domigrate
choice /c YN /n /m "Apply the database migrations now? [Y/N] "
if errorlevel 2 goto skipmigrate
:domigrate
call :migrate
if errorlevel 1 goto fail
goto aftermigrate
:skipmigrate
echo Skipped. The app reports unhealthy until the database is migrated.
:aftermigrate

echo.
echo [5/6] Starting the application ...
%COMPOSE% up -d app
if errorlevel 1 goto fail

echo.
echo [6/6] Waiting for http://localhost:%APP_PORT%/health ...
set /a n=0
:poll
curl.exe -fs -o nul "http://localhost:%APP_PORT%/health"
if not errorlevel 1 goto healthy
set /a n+=1
if %n% geq 30 goto unhealthy
ping -n 3 127.0.0.1 >nul
goto poll

:healthy
echo.
echo ===== Release %TAG% is running =====
echo Site:       http://localhost:%APP_PORT%
echo Binaries:   artifacts\publish
echo Image:      bookcart:%TAG%  (also bookcart:latest)
echo Logs:       docker logs -f bookcart-app
echo Stop:       %COMPOSE% down      (data stays in Docker volumes)
echo First admin: register in the site, then run
echo   docker exec -e SQLCMDPASSWORD=^<SA_PASSWORD from deploy\.env^> bookcart-sql /opt/mssql-tools18/bin/sqlcmd -C -S localhost -U sa -d BookDB -Q "UPDATE UserMaster SET UserTypeID = 1 WHERE Username = '<username>'"
if not defined AUTO_YES pause
exit /b 0

:unhealthy
echo.
echo The app did not become healthy within a minute. Last log lines:
docker logs --tail 30 bookcart-app
goto fail

:fail
echo.
echo ===== Release FAILED =====
if not defined AUTO_YES pause
exit /b 1

rem ---------------------------------------------------------------------------------------------------------

:make_env
echo Creating deploy\.env with generated secrets ...
for /f %%k in ('powershell -NoProfile -ExecutionPolicy Bypass -File "%~dp0lib\new-secret.ps1" 32') do set "GEN_JWT=%%k"
rem SQL Server wants upper case, lower case and digits: hex gives lower case and digits, the suffix adds an upper case letter.
for /f %%k in ('powershell -NoProfile -ExecutionPolicy Bypass -File "%~dp0lib\new-secret.ps1" 12') do set "GEN_SA=%%kAz1"
if "%GEN_JWT%"=="" exit /b 1
if "%GEN_SA%"=="" exit /b 1
> "%ENVFILE%" echo # Generated by scripts\release.bat. Contains secrets: never commit this file (it is git-ignored).
>> "%ENVFILE%" echo APP_PORT=8080
>> "%ENVFILE%" echo SQL_PORT=14331
>> "%ENVFILE%" echo SA_PASSWORD=%GEN_SA%
>> "%ENVFILE%" echo JWT_SECRET=%GEN_JWT%
>> "%ENVFILE%" echo # Set these to the public address of the site, with a trailing slash.
>> "%ENVFILE%" echo JWT_ISSUER=http://localhost:8080/
>> "%ENVFILE%" echo JWT_AUDIENCE=http://localhost:8080/
>> "%ENVFILE%" echo # Optional: Google Gemini key for AI book summaries.
>> "%ENVFILE%" echo GEMINI_API_KEY=
echo Created %ENVFILE%
echo Keep a safe copy: the SQL Server password cannot be recovered from the data volume.
exit /b 0

:backup
if not exist "%DEPLOY%\backups" mkdir "%DEPLOY%\backups"
set "BAK=BookDB_%TAG%.bak"
echo An existing database was found. Backing it up before any change ...
docker exec bookcart-sql mkdir -p /var/opt/mssql/backup
docker exec -e "SQLCMDPASSWORD=%SA_PASSWORD%" bookcart-sql /opt/mssql-tools18/bin/sqlcmd -C -S localhost -U sa -b -Q "BACKUP DATABASE [BookDB] TO DISK = N'/var/opt/mssql/backup/%BAK%' WITH INIT, CHECKSUM; RESTORE VERIFYONLY FROM DISK = N'/var/opt/mssql/backup/%BAK%' WITH CHECKSUM;"
if errorlevel 1 (
  echo Backup failed. Nothing was changed.
  exit /b 1
)
docker cp bookcart-sql:/var/opt/mssql/backup/%BAK% "%DEPLOY%\backups\%BAK%"
if errorlevel 1 (
  echo The backup exists inside the container but could not be copied out.
  exit /b 1
)
echo Backup saved and verified: deploy\backups\%BAK%
exit /b 0

:migrate
pushd "%ROOT%"
dotnet tool restore >nul
set "BOOKCART_EF_CONNECTION=Server=127.0.0.1,%SQL_PORT%;Database=BookDB;User Id=sa;Password=%SA_PASSWORD%;TrustServerCertificate=True"
dotnet ef database update --project BookCart --configuration Release
set "rc=%errorlevel%"
popd
exit /b %rc%
